In [5]:
import pandas as pd
import os
import splitfolders as sf

In [6]:
csv_path = "/Users/trinhnhathuy/pythonProject/ISIC-2019-venv/datasets/train/train-metadata.csv"
df = pd.read_csv(csv_path)
df

       Unnamed: 0       isic_id   patient_id  target
0               0  ISIC_0000000      dummy_0       0
1               1  ISIC_0000001      dummy_1       0
2               2  ISIC_0000002      dummy_2       1
3               3  ISIC_0000003      dummy_3       0
4               4  ISIC_0000004      dummy_4       1
...           ...           ...          ...     ...
25326       25326  ISIC_0073247  dummy_25326       0
25327       25327  ISIC_0073248  dummy_25327       0
25328       25328  ISIC_0073249  dummy_25328       1
25329       25329  ISIC_0073251  dummy_25329       0
25330       25330  ISIC_0073254  dummy_25330       0

[25331 rows x 4 columns]

In [7]:
# Group together rows whose value of "target" is 0 or 1
target_0 = df.loc[df['target'] == 0]
target_1 = df.loc[df['target'] == 1]
target_0

       Unnamed: 0       isic_id   patient_id  target
0               0  ISIC_0000000      dummy_0       0
1               1  ISIC_0000001      dummy_1       0
3               3  ISIC_0000003      dummy_3       0
5               5  ISIC_0000006      dummy_5       0
6               6  ISIC_0000007      dummy_6       0
...           ...           ...          ...     ...
25325       25325  ISIC_0073246  dummy_25325       0
25326       25326  ISIC_0073247  dummy_25326       0
25327       25327  ISIC_0073248  dummy_25327       0
25329       25329  ISIC_0073251  dummy_25329       0
25330       25330  ISIC_0073254  dummy_25330       0

[20809 rows x 4 columns]

In [8]:
# Take only the "isic_id" column
target_0_isic_id = target_0["isic_id"]
target_1_isic_id = target_1["isic_id"]
target_0_isic_id

0        ISIC_0000000
1        ISIC_0000001
3        ISIC_0000003
5        ISIC_0000006
6        ISIC_0000007
             ...
25325    ISIC_0073246
25326    ISIC_0073247
25327    ISIC_0073248
25329    ISIC_0073251
25330    ISIC_0073254
Name: isic_id, Length: 20809, dtype: object

In [9]:
# Move to the correct directory
cd /Users/trinhnhathuy/pythonProject/ISIC-2019-venv/datasets/train

/Users/trinhnhathuy/pythonProject/ISIC-2019-venv/datasets/train

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [10]:
# Sort image into the correct directory corresponding to their class
for element in target_0_isic_id:
    current_path = "{}.jpg".format(element)
    new_path = "target_0/{}.jpg".format(element)
    os.replace(current_path, new_path)

In [11]:
# Sort image into the correct directory corresponding to their class
for element in target_1_isic_id:
    current_path = "{}.jpg".format(element)
    new_path = "target_1/{}.jpg".format(element)
    os.replace(current_path, new_path)

In [14]:
# Use splitfolders package to split the train directory into test and validation subdirectory with ratio 80:20
input_folder = "/Users/trinhnhathuy/pythonProject/ISIC-2019-venv/datasets/train"
output_folder = "/Users/trinhnhathuy/pythonProject/ISIC-2019-venv/datasets/train_splitted"

sf.ratio(
    input_folder,
    output=output_folder,
    seed=1337,
    ratio=(0.8, 0.2),
    group_prefix=None,
    move=False)